---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

Ashraf - I dealt with fixing merge conflicts. So my friend pushed some changes to the remote. I made some local changes and committed but couldn't push. So I had to pull first but this caused conflicts. Therefore I had to edit merge conflicts and then commit and then push.

Nicholas - The experience in this lab is very good, we learned how to use git, using push, pull, add, and commit. Which will be very useful in the future, or even other classes. It has been a very productive class. Being able to track changes, collaborate with classmates, and manage version control is going to make group projects so much smoother.

Ishan Patel - I had problems downloading homebrew and git. I learned how to download git and create my own token. This will be very useful when completing future labs in groups.

Jackson Weaver - I learned how to link my github to my Rstudio in order
to be able to pull and push data from github or Rstudio. I learned that
adding a comment to the commit line can be used to tell if the current
push file in github is the same on my local machine in Rstudio.

